-------------Checkpoint_1--------------


-------------Instructions--------------

Refer to important NumPy functions. Some are listed below

●np.array()

●np.zeros()

●np.ones()

●np.reshape()

●np.concatenate()

●np.mean()

●np.sum()

●np.min()

●np.max()

●np.argmax()

●np.argmin()

●np.random.rand()

●np.random.randn()

●np.random.randint()

●np.dot

You will have to implement the functions listed above with one example

In [2]:
#Import numpy as np
import numpy as np

In [3]:
#1 Empty array
arr = np.array([])
arr

array([], dtype=float64)

In [5]:
#2 zero array
zero_arr = np.zeros((2,2))
zero_arr

array([[0., 0.],
       [0., 0.]])

In [21]:
#3 ones array
one_arr = np.ones((3,3))
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#4 Reshaping array
reshape_arr = np.reshape(np.arange(1,10),(3,3))
reshape_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#5 Concatenate arrays
concatenated_arr = np.concatenate((zero_arr, one_arr), axis=0)
concatenated_arr

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [11]:
#6 Calculate the mean of an array
mean_value = np.mean(reshape_arr)
mean_value

5.0

In [12]:
#7 Calculate the sum of array elements
sum_value = np.sum(reshape_arr)
sum_value

45

In [13]:
#8 Find the minimum value in an array
min_value = np.min(reshape_arr)
min_value

1

In [14]:
#9 Find the maximum value in an array
max_value = np.max(reshape_arr)
max_value

9

In [15]:
#10 Find the index of the maximum value in an array
argmax_index = np.argmax(reshape_arr)
argmax_index

8

In [16]:
#11 Find the index of the minimum value in an array
argmin_index = np.argmin(reshape_arr)
argmin_index

0

In [17]:
#12 Generate random values in a given shape
random_values = np.random.rand(2, 2)
random_values

array([[0.8757186 , 0.03292596],
       [0.62813825, 0.43149314]])

In [18]:
#13 Generate random values from a standard normal distribution
random_normal_values = np.random.randn(3, 3)
random_normal_values

array([[-0.22167829,  0.0892993 , -0.17704286],
       [ 0.84532699,  0.20621554,  2.18010191],
       [-0.45694508, -0.33805863,  0.21980559]])

In [19]:
#14 Generate random integers
random_integers = np.random.randint(1, 10, size=(2, 2))
random_integers

array([[1, 4],
       [8, 9]])

In [22]:
#15 Dot product of two arrays
dot_product = np.dot(reshape_arr, one_arr)
dot_product

array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])